@domain = http://localhost:3007
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MjcyODI2YWQ4NzI1YWQ5Y2U3MTljNCIsImVtYWlsIjoicHJ1ZWJhQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzY0MTczODYzLCJleHAiOjE3NjQxNzQ3NjN9.w651i-adDS0iUrqKieJKMIr5g8DYZv3aWEiDi6VXevo

### REGISTER USER
POST {{domain}}/auth/register
Content-Type: application/json

{
    "email": "prueba@gmail.com",
    "username": "prueba",
    "password": "123456"
}

### Login
POST {{domain}}/auth/login
Content-Type: application/json

{
    "email": "prueba@gmail.com",
    "password": "123456"
}

### Refresh Token
POST {{domain}}/auth/refresh
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MjVhMjk5NjcyMDYzZGU2YWYyMTMwMCIsImlhdCI6MTc2NDA3NDQ0MywiZXhwIjoxNzY2NjY2NDQzfQ.BerYGeRUwAvxWefD5zAlw_a91w00UH9OM1DsCZZ4UKc"
}
### Game
POST {{domain}}/games/save
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "textId": "6926fa6f727549c276c5a06d",
  "rawWPM": 82,
  "adjustedWPM": 78,
  "accuracy": 95.1,
  "mode": "normal",
  "charactersTyped": 420,
  "charactersCorrect": 399,
  "duration": 60,
  "startedAt": "2025-01-26T12:30:12.000Z",
  "finishedAt": "2025-01-26T12:31:12.000Z"
}
