@domain = http://localhost:3007
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5Mjk5MDRjNzkyZWM4MjNlNDE3OGM5NyIsImVtYWlsIjoicHJ1ZWJhMkBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTc2NDMzMTg4NCwiZXhwIjoxNzY0MzMyNzg0fQ.RUzK7BVQreBzTvrZgH-tcLt2JGwUO_A6VlzGHEG4jpc
POST {{domain}}/auth/register
Content-Type: application/json

{
    "email": "prueba2@gmail.com",
    "username": "prueba2",
    "password": "123456"
}

### Login
POST {{domain}}/auth/login
Content-Type: application/json

{
    "email": "prueba2@gmail.com",
    "password": "123456"
}

### Refresh Token
POST {{domain}}/auth/refresh
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5Mjk5MDRjNzkyZWM4MjNlNDE3OGM5NyIsImlhdCI6MTc2NDMzMTg1OSwiZXhwIjoxNzY2OTIzODU5fQ.LpAHQSFmmIgO7sXjGEbJNMoHrL3FDbJWUWG2eOzjwoY"
}
### Game
POST {{domain}}/games/save
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "textId": "6926fa6f727549c276c5a06d",
  "rawWPM": 84,
  "adjustedWPM": 80,
  "accuracy": 97.1,
  "mode": "normal",
  "charactersTyped": 422,
  "charactersCorrect": 399,
  "duration": 60,
  "startedAt": "2025-01-26T12:30:12.000Z",
  "finishedAt": "2025-01-26T12:31:12.000Z"
}

###Games History
GET {{domain}}/games/history
Content-Type: application/json
Authorization: Bearer {{token}}

### Metrics user
GET {{domain}}/games/me/metrics
Content-Type: application/json
Authorization: Bearer {{token}}

###Logout
DELETE {{domain}}/auth/logout
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "refreshToken_id": "4d8bf28019bfdc589d6da64e166e1781"
}